export interface MockTask {
  id: string;
  title: string;
  slug: string;
  type: "coding" | "bug_fix" | "refactor" | "code_review" | "system_design" | "database" | "deployment" | "debug";
  difficulty: "easy" | "medium" | "hard";
  category: string;
  careerLevel: string;
  statement: string;
  inputFormat: string;
  outputFormat: string;
  constraints: string;
  sampleInput: string;
  sampleOutput: string;
  hiddenTests: { input: string; output: string }[];
  starterCode: Record<string, string>;
  expReward: number;
  salaryReward: number;
  reputationReward: number;
  deadlineHours: number;
  priority: "low" | "medium" | "high" | "critical";
  orderIndex: number;
}

export const MOCK_TASKS: MockTask[] = [
  {
    id: "1",
    title: "Hello World — In ra màn hình",
    slug: "hello-world",
    type: "coding",
    difficulty: "easy",
    category: "Cơ bản",
    careerLevel: "intern",
    statement: `## Mô tả\nViết chương trình in ra dòng chữ **"Hello, World!"** trên màn hình.\n\nĐây là nhiệm vụ đầu tiên trong hành trình sự nghiệp của bạn. Hãy chứng minh rằng bạn biết cách chạy một chương trình cơ bản!`,
    inputFormat: "Không có input.",
    outputFormat: 'In ra dòng chữ `Hello, World!`',
    constraints: "Không có.",
    sampleInput: "",
    sampleOutput: "Hello, World!",
    hiddenTests: [{ input: "", output: "Hello, World!" }],
    starterCode: {
      python: '# Viết code của bạn ở đây\nprint("Hello, World!")',
      javascript: '// Viết code của bạn ở đây\nconsole.log("Hello, World!");',
      cpp: '#include <iostream>\nusing namespace std;\n\nint main() {\n    // Viết code của bạn ở đây\n    cout << "Hello, World!" << endl;\n    return 0;\n}',
      java: 'public class Main {\n    public static void main(String[] args) {\n        // Viết code của bạn ở đây\n        System.out.println("Hello, World!");\n    }\n}',
    },
    expReward: 10,
    salaryReward: 50000,
    reputationReward: 2,
    deadlineHours: 24,
    priority: "low",
    orderIndex: 0,
  },
  {
    id: "2",
    title: "Tính tổng hai số",
    slug: "sum-two-numbers",
    type: "coding",
    difficulty: "easy",
    category: "Cơ bản",
    careerLevel: "intern",
    statement: `## Mô tả\nCho hai số nguyên **a** và **b**. Hãy tính và in ra tổng của chúng.\n\n### Ví dụ\nNếu a = 3, b = 5 thì kết quả là 8.`,
    inputFormat: "Hai số nguyên a và b trên cùng một dòng, cách nhau bởi dấu cách.",
    outputFormat: "In ra tổng của a và b.",
    constraints: "-10^9 ≤ a, b ≤ 10^9",
    sampleInput: "3 5",
    sampleOutput: "8",
    hiddenTests: [
      { input: "3 5", output: "8" },
      { input: "0 0", output: "0" },
      { input: "-1 1", output: "0" },
      { input: "1000000000 1000000000", output: "2000000000" },
    ],
    starterCode: {
      python: "a, b = map(int, input().split())\nprint(a + b)",
      javascript: "const [a, b] = require('fs').readFileSync('/dev/stdin', 'utf8').trim().split(' ').map(Number);\nconsole.log(a + b);",
      cpp: '#include <iostream>\nusing namespace std;\n\nint main() {\n    long long a, b;\n    cin >> a >> b;\n    cout << a + b << endl;\n    return 0;\n}',
      java: 'import java.util.Scanner;\n\npublic class Main {\n    public static void main(String[] args) {\n        Scanner sc = new Scanner(System.in);\n        long a = sc.nextLong();\n        long b = sc.nextLong();\n        System.out.println(a + b);\n    }\n}',
    },
    expReward: 10,
    salaryReward: 50000,
    reputationReward: 2,
    deadlineHours: 24,
    priority: "low",
    orderIndex: 1,
  },
  {
    id: "3",
    title: "Kiểm tra số chẵn lẻ",
    slug: "even-odd",
    type: "coding",
    difficulty: "easy",
    category: "Điều kiện",
    careerLevel: "intern",
    statement: `## Mô tả\nCho số nguyên **n**. Hãy kiểm tra xem n là số chẵn hay số lẻ.\n\n- Nếu chẵn, in ra **"Even"**\n- Nếu lẻ, in ra **"Odd"**`,
    inputFormat: "Một số nguyên n.",
    outputFormat: 'In ra "Even" hoặc "Odd".',
    constraints: "-10^9 ≤ n ≤ 10^9",
    sampleInput: "4",
    sampleOutput: "Even",
    hiddenTests: [
      { input: "4", output: "Even" },
      { input: "7", output: "Odd" },
      { input: "0", output: "Even" },
      { input: "-3", output: "Odd" },
    ],
    starterCode: {
      python: "n = int(input())\n# Viết code kiểm tra chẵn lẻ",
      javascript: "const n = parseInt(require('fs').readFileSync('/dev/stdin', 'utf8').trim());\n// Viết code kiểm tra chẵn lẻ",
      cpp: '#include <iostream>\nusing namespace std;\n\nint main() {\n    int n;\n    cin >> n;\n    // Viết code kiểm tra chẵn lẻ\n    return 0;\n}',
      java: 'import java.util.Scanner;\n\npublic class Main {\n    public static void main(String[] args) {\n        Scanner sc = new Scanner(System.in);\n        int n = sc.nextInt();\n        // Viết code kiểm tra chẵn lẻ\n    }\n}',
    },
    expReward: 10,
    salaryReward: 50000,
    reputationReward: 2,
    deadlineHours: 48,
    priority: "medium",
    orderIndex: 2,
  },
  {
    id: "4",
    title: "FizzBuzz",
    slug: "fizzbuzz",
    type: "coding",
    difficulty: "easy",
    category: "Vòng lặp",
    careerLevel: "intern",
    statement: `## Mô tả\nCho số nguyên dương **n**. In ra các số từ 1 đến n, nhưng:\n- Nếu số chia hết cho 3, in **"Fizz"**\n- Nếu số chia hết cho 5, in **"Buzz"**\n- Nếu số chia hết cho cả 3 và 5, in **"FizzBuzz"**\n- Còn lại in số đó`,
    inputFormat: "Một số nguyên dương n.",
    outputFormat: "Mỗi kết quả trên một dòng.",
    constraints: "1 ≤ n ≤ 100",
    sampleInput: "5",
    sampleOutput: "1\n2\nFizz\n4\nBuzz",
    hiddenTests: [
      { input: "5", output: "1\n2\nFizz\n4\nBuzz" },
      { input: "15", output: "1\n2\nFizz\n4\nBuzz\nFizz\n7\n8\nFizz\nBuzz\n11\nFizz\n13\n14\nFizzBuzz" },
    ],
    starterCode: {
      python: "n = int(input())\nfor i in range(1, n + 1):\n    # Viết logic FizzBuzz",
      javascript: "const n = parseInt(require('fs').readFileSync('/dev/stdin', 'utf8').trim());\nfor (let i = 1; i <= n; i++) {\n  // Viết logic FizzBuzz\n}",
      cpp: '#include <iostream>\nusing namespace std;\n\nint main() {\n    int n;\n    cin >> n;\n    for (int i = 1; i <= n; i++) {\n        // Viết logic FizzBuzz\n    }\n    return 0;\n}',
      java: 'import java.util.Scanner;\n\npublic class Main {\n    public static void main(String[] args) {\n        Scanner sc = new Scanner(System.in);\n        int n = sc.nextInt();\n        for (int i = 1; i <= n; i++) {\n            // Viết logic FizzBuzz\n        }\n    }\n}',
    },
    expReward: 15,
    salaryReward: 75000,
    reputationReward: 3,
    deadlineHours: 24,
    priority: "low",
    orderIndex: 3,
  },
  {
    id: "5",
    title: "Đảo ngược chuỗi",
    slug: "reverse-string",
    type: "coding",
    difficulty: "easy",
    category: "Chuỗi",
    careerLevel: "intern",
    statement: `## Mô tả\nCho một chuỗi ký tự **s**. Hãy in ra chuỗi đảo ngược của nó.`,
    inputFormat: "Một chuỗi s.",
    outputFormat: "Chuỗi đảo ngược.",
    constraints: "1 ≤ |s| ≤ 10^5",
    sampleInput: "hello",
    sampleOutput: "olleh",
    hiddenTests: [
      { input: "hello", output: "olleh" },
      { input: "a", output: "a" },
      { input: "abcde", output: "edcba" },
    ],
    starterCode: {
      python: "s = input()\n# Đảo ngược chuỗi s",
      javascript: "const s = require('fs').readFileSync('/dev/stdin', 'utf8').trim();\n// Đảo ngược chuỗi s",
      cpp: '#include <iostream>\n#include <algorithm>\nusing namespace std;\n\nint main() {\n    string s;\n    cin >> s;\n    // Đảo ngược chuỗi s\n    return 0;\n}',
      java: 'import java.util.Scanner;\n\npublic class Main {\n    public static void main(String[] args) {\n        Scanner sc = new Scanner(System.in);\n        String s = sc.next();\n        // Đảo ngược chuỗi s\n    }\n}',
    },
    expReward: 10,
    salaryReward: 50000,
    reputationReward: 2,
    deadlineHours: 24,
    priority: "low",
    orderIndex: 4,
  },
  {
    id: "6",
    title: "Fix bug: Vòng lặp vô hạn",
    slug: "fix-infinite-loop",
    type: "bug_fix",
    difficulty: "medium",
    category: "Debug",
    careerLevel: "junior",
    statement: `## Mô tả\nChương trình dưới đây tính tổng các số từ 1 đến n, nhưng nó bị **vòng lặp vô hạn**.\n\nHãy tìm và sửa bug.\n\n### Code bị lỗi (Python)\n\`\`\`python\nn = int(input())\ntotal = 0\ni = 1\nwhile i <= n:\n    total += i\n    # Bug: thiếu i += 1\nprint(total)\n\`\`\``,
    inputFormat: "Một số nguyên dương n.",
    outputFormat: "Tổng các số từ 1 đến n.",
    constraints: "1 ≤ n ≤ 10^6",
    sampleInput: "5",
    sampleOutput: "15",
    hiddenTests: [
      { input: "5", output: "15" },
      { input: "10", output: "55" },
      { input: "100", output: "5050" },
    ],
    starterCode: {
      python: "n = int(input())\ntotal = 0\ni = 1\nwhile i <= n:\n    total += i\n    # Fix bug ở đây\nprint(total)",
      javascript: "const n = parseInt(require('fs').readFileSync('/dev/stdin', 'utf8').trim());\nlet total = 0;\nlet i = 1;\nwhile (i <= n) {\n  total += i;\n  // Fix bug ở đây\n}\nconsole.log(total);",
      cpp: '#include <iostream>\nusing namespace std;\n\nint main() {\n    int n;\n    cin >> n;\n    long long total = 0;\n    int i = 1;\n    while (i <= n) {\n        total += i;\n        // Fix bug ở đây\n    }\n    cout << total << endl;\n    return 0;\n}',
      java: 'import java.util.Scanner;\n\npublic class Main {\n    public static void main(String[] args) {\n        Scanner sc = new Scanner(System.in);\n        int n = sc.nextInt();\n        long total = 0;\n        int i = 1;\n        while (i <= n) {\n            total += i;\n            // Fix bug ở đây\n        }\n        System.out.println(total);\n    }\n}',
    },
    expReward: 25,
    salaryReward: 150000,
    reputationReward: 5,
    deadlineHours: 12,
    priority: "high",
    orderIndex: 5,
  },
  {
    id: "7",
    title: "Tìm số lớn nhất trong mảng",
    slug: "find-max",
    type: "coding",
    difficulty: "medium",
    category: "Mảng",
    careerLevel: "junior",
    statement: `## Mô tả\nCho một mảng gồm **n** số nguyên. Tìm và in ra số lớn nhất trong mảng.`,
    inputFormat: "Dòng 1: số nguyên n.\nDòng 2: n số nguyên cách nhau bởi dấu cách.",
    outputFormat: "Số lớn nhất trong mảng.",
    constraints: "1 ≤ n ≤ 10^5, -10^9 ≤ a_i ≤ 10^9",
    sampleInput: "5\n3 1 4 1 5",
    sampleOutput: "5",
    hiddenTests: [
      { input: "5\n3 1 4 1 5", output: "5" },
      { input: "1\n42", output: "42" },
      { input: "3\n-1 -5 -3", output: "-1" },
    ],
    starterCode: {
      python: "n = int(input())\narr = list(map(int, input().split()))\n# Tìm max",
      javascript: "const lines = require('fs').readFileSync('/dev/stdin', 'utf8').trim().split('\\n');\nconst n = parseInt(lines[0]);\nconst arr = lines[1].split(' ').map(Number);\n// Tìm max",
      cpp: '#include <iostream>\nusing namespace std;\n\nint main() {\n    int n;\n    cin >> n;\n    // Đọc mảng và tìm max\n    return 0;\n}',
      java: 'import java.util.Scanner;\n\npublic class Main {\n    public static void main(String[] args) {\n        Scanner sc = new Scanner(System.in);\n        int n = sc.nextInt();\n        // Đọc mảng và tìm max\n    }\n}',
    },
    expReward: 25,
    salaryReward: 150000,
    reputationReward: 5,
    deadlineHours: 24,
    priority: "medium",
    orderIndex: 6,
  },
  {
    id: "8",
    title: "Sắp xếp mảng tăng dần",
    slug: "sort-array",
    type: "coding",
    difficulty: "medium",
    category: "Sắp xếp",
    careerLevel: "junior",
    statement: `## Mô tả\nCho mảng gồm **n** số nguyên. Sắp xếp mảng theo thứ tự tăng dần và in ra.`,
    inputFormat: "Dòng 1: n. Dòng 2: n số nguyên.",
    outputFormat: "Mảng đã sắp xếp, cách nhau bởi dấu cách.",
    constraints: "1 ≤ n ≤ 10^5",
    sampleInput: "5\n5 3 1 4 2",
    sampleOutput: "1 2 3 4 5",
    hiddenTests: [
      { input: "5\n5 3 1 4 2", output: "1 2 3 4 5" },
      { input: "1\n1", output: "1" },
      { input: "3\n3 3 3", output: "3 3 3" },
    ],
    starterCode: {
      python: "n = int(input())\narr = list(map(int, input().split()))\n# Sắp xếp mảng",
      javascript: "const lines = require('fs').readFileSync('/dev/stdin', 'utf8').trim().split('\\n');\nconst n = parseInt(lines[0]);\nconst arr = lines[1].split(' ').map(Number);\n// Sắp xếp mảng",
      cpp: '#include <iostream>\n#include <algorithm>\nusing namespace std;\n\nint main() {\n    int n;\n    cin >> n;\n    // Đọc, sắp xếp, in\n    return 0;\n}',
      java: 'import java.util.*;\n\npublic class Main {\n    public static void main(String[] args) {\n        Scanner sc = new Scanner(System.in);\n        int n = sc.nextInt();\n        // Đọc, sắp xếp, in\n    }\n}',
    },
    expReward: 25,
    salaryReward: 150000,
    reputationReward: 5,
    deadlineHours: 24,
    priority: "medium",
    orderIndex: 7,
  },
  {
    id: "9",
    title: "Fibonacci",
    slug: "fibonacci",
    type: "coding",
    difficulty: "medium",
    category: "Đệ quy",
    careerLevel: "junior",
    statement: `## Mô tả\nCho số nguyên dương **n**. In ra số Fibonacci thứ n.\n\nDãy Fibonacci: F(0)=0, F(1)=1, F(n)=F(n-1)+F(n-2).`,
    inputFormat: "Một số nguyên n.",
    outputFormat: "Số Fibonacci thứ n.",
    constraints: "0 ≤ n ≤ 45",
    sampleInput: "10",
    sampleOutput: "55",
    hiddenTests: [
      { input: "10", output: "55" },
      { input: "0", output: "0" },
      { input: "1", output: "1" },
      { input: "20", output: "6765" },
    ],
    starterCode: {
      python: "n = int(input())\n# Tính Fibonacci thứ n",
      javascript: "const n = parseInt(require('fs').readFileSync('/dev/stdin', 'utf8').trim());\n// Tính Fibonacci thứ n",
      cpp: '#include <iostream>\nusing namespace std;\n\nint main() {\n    int n;\n    cin >> n;\n    // Tính Fibonacci thứ n\n    return 0;\n}',
      java: 'import java.util.Scanner;\n\npublic class Main {\n    public static void main(String[] args) {\n        Scanner sc = new Scanner(System.in);\n        int n = sc.nextInt();\n        // Tính Fibonacci thứ n\n    }\n}',
    },
    expReward: 25,
    salaryReward: 150000,
    reputationReward: 5,
    deadlineHours: 48,
    priority: "medium",
    orderIndex: 8,
  },
  {
    id: "10",
    title: "Thiết kế Database Schema",
    slug: "design-db-schema",
    type: "database",
    difficulty: "hard",
    category: "Database",
    careerLevel: "senior",
    statement: `## Mô tả\nViết chương trình nhận input là số lượng bảng **n**, sau đó in ra danh sách tên các bảng cơ bản cho một hệ thống e-commerce.\n\nMỗi bảng trên một dòng, theo thứ tự alphabet.`,
    inputFormat: "Số nguyên n (số bảng cần in).",
    outputFormat: "n tên bảng, mỗi dòng một bảng, theo thứ tự alphabet.",
    constraints: "1 ≤ n ≤ 10",
    sampleInput: "3",
    sampleOutput: "categories\norders\nproducts",
    hiddenTests: [
      { input: "3", output: "categories\norders\nproducts" },
      { input: "5", output: "categories\ncustomers\norders\nproducts\nreviews" },
    ],
    starterCode: {
      python: 'tables = ["products", "orders", "customers", "categories", "reviews",\n         "payments", "shipping", "inventory", "coupons", "wishlists"]\nn = int(input())\n# In ra n bảng đầu tiên (sorted)',
      javascript: 'const tables = ["products","orders","customers","categories","reviews",\n  "payments","shipping","inventory","coupons","wishlists"];\nconst n = parseInt(require("fs").readFileSync("/dev/stdin","utf8").trim());\n// In ra n bảng đầu tiên (sorted)',
      cpp: '#include <iostream>\n#include <vector>\n#include <algorithm>\nusing namespace std;\n\nint main() {\n    int n;\n    cin >> n;\n    // Tạo danh sách bảng và in\n    return 0;\n}',
      java: 'import java.util.*;\n\npublic class Main {\n    public static void main(String[] args) {\n        Scanner sc = new Scanner(System.in);\n        int n = sc.nextInt();\n        // Tạo danh sách bảng và in\n    }\n}',
    },
    expReward: 50,
    salaryReward: 500000,
    reputationReward: 15,
    deadlineHours: 168,
    priority: "critical",
    orderIndex: 9,
  },
];

export function getTaskBySlug(slug: string): MockTask | undefined {
  return MOCK_TASKS.find((t) => t.slug === slug);
}
